Don't implicitly chain exceptions when accessing non-existent storage attributes (#7734)
This PR changes the traceback when a user tries to access attributes on
`Data` that doesn't exist:

```python
import torch_geometric

data = torch_geometric.data.Data()
data.asdf
```

## Before

```diff
Traceback (most recent call last):
  File "/workspaces/pytorch_geometric/torch_geometric/data/storage.py", line 80, in __getattr__
    return self[key]
  File "/workspaces/pytorch_geometric/torch_geometric/data/storage.py", line 105, in __getitem__
    return self._mapping[key]
KeyError: 'asdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/pytorch_geometric/test.py", line 4, in <module>
    data.asdf
  File "/workspaces/pytorch_geometric/torch_geometric/data/data.py", line 475, in __getattr__
    return getattr(self._store, key)
  File "/workspaces/pytorch_geometric/torch_geometric/data/storage.py", line 82, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'asdf'
```

## After

```
Traceback (most recent call last):
  File "/workspaces/pytorch_geometric/test.py", line 4, in <module>
    data.asdf
  File "/workspaces/pytorch_geometric/torch_geometric/data/data.py", line 475, in __getattr__
    return getattr(self._store, key)
  File "/workspaces/pytorch_geometric/torch_geometric/data/storage.py", line 82, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'asdf'
```

## Alternative

By explicitly chaining exceptions, one of the lines in the error
changes:
```diff
-       except KeyError:
+       except KeyError as e:
            raise AttributeError(
-               f"'{self.__class__.__name__}' object has no attribute '{key}'")
+               f"'{self.__class__.__name__}' object has no attribute '{key}'") from e
```

```diff
- During handling of the above exception, another exception occurred:
+ The above exception was the direct cause of the following exception:
```

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>