Fix `HeteroLinear` usage for mixed precision (#7473)
This PR fixes an issue with the `HeteroLinear` module, which crashes in
the forward pass if it us used within a `torch.cuda.amp.autocast`
environment for mixed precision.

Consider the following example:
```python
import torch
from torch_geometric.nn.dense.linear import HeteroLinear

x = torch.randn(3, 16, device='cuda:0')
type_vec = torch.tensor([0, 1, 2], device='cuda:0')
lin = HeteroLinear(16, 32, num_types=3).to('cuda:0')
lin.use_segmm = 0
with torch.cuda.amp.autocast():
    out_no_segmm = lin(x, type_vec)
```

We obtain the following trace (Python 3.10, current nightly, CUDA 11.7):
```
Traceback (most recent call last):
  File "/home/jan/git/gerd/pyg_test.py", line 9, in <module>
    out_no_segmm = lin(x, type_vec)
  File "/home/jan/miniconda3/envs/gerd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jan/miniconda3/envs/gerd/lib/python3.10/site-packages/torch_geometric/nn/dense/linear.py", line 275, in forward
    out[mask] = F.linear(x[mask], self.weight[i].T)
RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Half for the source.
```

The issue is caused by `F.linear` changing the dtype on the fly. An
additional cast is needed in this case.

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: rusty1s <matthias.fey@tu-dortmund.de>